name: Run Pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Run tests with coverage and HTML report
      run: |
        mkdir -p reports
        pytest \
          --cov=utils \
          --cov=fixtures \
          --cov-report=term-missing \
          --cov-report=xml \
          --cov-fail-under=80 \
          --html=reports/pytest_report.html \
          --self-contained-html \
          -v

    - name: Upload Pytest HTML report
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report
        path: reports/pytest_report.html

    - name: Upload coverage XML report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-xml-report
        path: coverage.xml
